includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser.yaml

variables:
  main: "."
  binary_name: skate
  description: "A personal key value store 🛼"
  github_url: "https://github.com/charmbracelet/skate"
  maintainer: "Christian Rocha <christian@charm.sh>"
  brew_commit_author_name: "Christian Rocha"
  brew_commit_author_email: "christian@charm.sh"
