includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-semi.yaml

variables:
  binary_name: skate
  description: "A tasty, self-hostable Git server for the command line🍦"
  github_url: "https://github.com/charmbracelet/soft-serve"
  maintainer: "Christian Rocha <christian@charm.sh>"
  brew_commit_author_name: "Christian Rocha"
  brew_commit_author_email: "christian@charm.sh"
